<a href="https://colab.research.google.com/github/Sarav-J/231801158_PODS/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
my_arr=np.arange(10)
print(my_arr)
print(type(my_arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
my_list = list(range(10))
print(my_list)
print(type(my_list))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [ ]:
import numpy as np
import sys
S=range(1000)
print("Size of each element of list in bytes: ",sys.getsizeof(S))
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))
D=np.arange(1000)
print("Size of each element of the Numpy array in bytes: ",D.itemsize)
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)
print(type(S))
print(type(D))

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000
<class 'range'>
<class 'numpy.ndarray'>


In [ ]:
arr=np.array(42)
print(arr)

42


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimension :',arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimension : 5


In [ ]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print("Shape= ",data.shape)
print("Type= ",data.dtype)
print("Data = ", data)
print("\nAns1 = ",data * 10)
print("\nAns2= ",data+data)

Shape=  (2, 3)
Type=  float64
Data =  [[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]

Ans1 =  [[ 15.  -1.  30.]
 [  0. -30.  65.]]

Ans2=  [[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]


In [ ]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)
print(type(arr))
print(arr)
print("\n",arr.dtype)

<class 'numpy.ndarray'>
[1 2 3 4 5]

 int64


In [ ]:
zeros_arr = np.zeros((5,2))
eros_arr = np.zeros(5)
print(zeros_arr)
zeros_arr = np.zeros((2,3))
print(zeros_arr)
print("Data type of the array: ",zeros_arr.dtype)
zeros_arr_int=np.zeros((3,3),dtype=np.int16)
print("\n Array of zeros with integer elements:\n",zeros_arr_int)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
Data type of the array:  float64

 Array of zeros with integer elements:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
ones_arr = np.ones(6)
print(ones_arr)
ones_arr = np.ones((3,2,4)) # 3- depth, 2- rows, 4 -colums
print("\n",ones_arr)
print("\n ndim= ",ones_arr.ndim)
print("\nData type of the array: ",ones_arr.dtype)
ones_arr_int = np.ones((2,2), dtype=np.int16)
print("\nArray of ones with integer elements: \n",ones_arr_int)

[1. 1. 1. 1. 1. 1.]

 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

 ndim=  3

Data type of the array:  float64

Array of ones with integer elements: 
 [[1 1]
 [1 1]]


In [ ]:
empty_arr = np.empty((3,2))
print(empty_arr)
print("\nData type of the array: ",empty_arr.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]

Data type of the array:  float64


In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)
identity_matrix=np.eye(4)
print("\n",identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np. float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)


float64
int32


In [ ]:
arr = np.array([1, 2, 3])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('f')
print("After converting: ", new_arr, new_arr.dtype)


Before converting:  [1 2 3] int64
After converting:  [1. 2. 3.] float32


In [ ]:
arr = np.array([1.1, 2.2, 3.3])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('i')
print("After converting: ", new_arr, new_arr.dtype)

Before converting:  [1.1 2.2 3.3] float64
After converting:  [1 2 3] int32


In [ ]:
import numpy as np
arr = np.array(['1.1', '2.2', '-3.3'])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('f')
print("After converting: ", new_arr, new_arr.dtype)

Before converting:  ['1.1' '2.2' '-3.3'] <U4
After converting:  [ 1.1  2.2 -3.3] float32


In [ ]:
arr = np.array(['1.1', '2.2', 'abc'])
print("Before converting: ", arr, arr.dtype)
try:
  new_arr = arr.astype (np. float64)
  print("After converting: ", new_arr, new_arr.dtype)
except ValueError as e:
  print("Conversion failed: ", e)


Before converting:  ['1.1' '2.2' 'abc'] <U3
Conversion failed:  could not convert string to float: np.str_('abc')


In [ ]:
arr1 = np.arange(10)
arr2 = np.random. randn (10)
print("array 1\n", arr1, arr1.dtype)
print("Array 2 \n", arr2, arr2.dtype)
new_arr = arr1.astype (arr2.dtype)
print("New Array \n", new_arr, new_arr.dtype)

array 1
 [0 1 2 3 4 5 6 7 8 9] int64
Array 2 
 [-1.66811799 -0.00752876 -0.37591697  0.7113991  -0.18891834  1.11854184
  0.61655905 -0.23283058  1.139259   -0.17865964] float64
New Array 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [ ]:
str_arr = np.array(['hello', 'world', 'numpy'])
print(str_arr)

['hello' 'world' 'numpy']
